version: '3'

services:
    reverse_proxy:
        image: nginx:1.19
        volumes:
          - "$PWD/docker-files/etc/nginx/nginx.conf:/etc/nginx/nginx.conf"
        ports:
          - "80:80"
        depends_on:
          - db
          - app

    app:
        build:
            context: ./app
            dockerfile: Dockerfile.go
        command: "make build run"
        working_dir: "/go/src/isucon"
        volumes:
          - "$PWD/app:/go/src/isucon"
        environment:
            GOPATH: "/go"

    db:
        image: mysql:5.7
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_ROOT_PASSWORD: ""
            MYSQL_DATABASE: "isucon"
            MYSQL_USER: "isucon"
            MYSQL_PASSWORD: "isucon"
        volumes:
          - "$PWD/docker-files/init.sql.gz:/docker-entrypoint-initdb.d/init.sql.gz"
